import { useState, useEffect } from "react";
import {
  Search,
  CheckCircle2,
  Clock,
  XCircle,
  Loader2,
  FilePlus,
  CalendarDays,
  ChevronDown,
  ChevronRight,
  Wallet,
  HandCoins,
  AlertTriangle,
  Trash2,
} from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { formatRupiah, formatDateShort } from "@/lib/format";
import type { Bill, Payment, APIResponse } from "@/types";
import { toast } from "sonner";
import api from "@/lib/api";
import { useResident } from "@/context/ResidentContext";
import ConfirmModal from "@/components/ConfirmModal";

export default function Billing() {
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedPayment, setExpandedPayment] = useState<number | null>(null);

  // Real Data states
  const { residents, fetchResidents } = useResident();
  const [bills, setBills] = useState<Bill[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);

  const [isLoadingBills, setIsLoadingBills] = useState(true);
  const [isLoadingPayments, setIsLoadingPayments] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Bill Generation Modals
  const [isAutoGenerateDialogOpen, setIsAutoGenerateDialogOpen] =
    useState(false);
  const [isManualGenerateDialogOpen, setIsManualGenerateDialogOpen] =
    useState(false);
  const [manualForm, setManualForm] = useState({
    resident_id: "",
    duration: "1",
  });

  // Single Payment Modal
  const [isSinglePaymentOpen, setIsSinglePaymentOpen] = useState(false);
  const [selectedSingleBill, setSelectedSingleBill] = useState<Bill | null>(
    null,
  );
  const [singlePaymentAmount, setSinglePaymentAmount] = useState<string>("");

  // Multi Payment Modal
  const [isMultiPaymentOpen, setIsMultiPaymentOpen] = useState(false);
  const [multiForm, setMultiForm] = useState({
    resident_id: "",
    total_amount: "",
  });
  const [residentBills, setResidentBills] = useState<Bill[]>([]);
  const [isLoadingResidentBills, setIsLoadingResidentBills] = useState(false);
  const [selectedMultiBills, setSelectedMultiBills] = useState<number[]>([]);
  const [selectedBillForDelete, setSelectedBillForDelete] = useState<
    number | null
  >(null);
  const [isDeleting, setIsDeleting] = useState(false);

  // Fetching Data
  const fetchBills = async () => {
    setIsLoadingBills(true);
    try {
      const response = await api.get<APIResponse<Bill[]>>("/bills");
      if (response.data.success) {
        setBills(response.data.data);
      }
    } catch (error) {
      console.error("Error fetching bills:", error);
      toast.error("Gagal mengambil data tagihan");
    } finally {
      setIsLoadingBills(false);
    }
  };

  const fetchPayments = async () => {
    setIsLoadingPayments(true);
    try {
      const response = await api.get<APIResponse<Payment[]>>("/payments");
      if (response.data.success) {
        setPayments(response.data.data);
      }
    } catch (error) {
      console.error("Error fetching payments:", error);
      toast.error("Gagal mengambil data riwayat pembayaran");
    } finally {
      setIsLoadingPayments(false);
    }
  };

  useEffect(() => {
    fetchBills();
    fetchPayments();
    fetchResidents();
  }, [fetchResidents]);

  // Filtering Bills
  const filteredBills = bills.filter((b) => {
    const resName = b.resident_name || "";
    const houseNum = b.house_number || "";
    return (
      resName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      houseNum.toLowerCase().includes(searchQuery.toLowerCase())
    );
  });

  // ========== BILL GENERATION ==========
  const handleAutoGenerate = async () => {
    setIsSubmitting(true);
    try {
      const payload = { period_start: new Date().toISOString().split("T")[0] };
      const response = await api.post("/bills/generate", payload);
      if (response.data.success) {
        toast.success(
          response.data.message || "Tagihan otomatis berhasil dibuat",
        );
        setIsAutoGenerateDialogOpen(false);
        fetchBills();
      }
    } catch (error: any) {
      toast.error(
        error.response?.data?.message || "Gagal membuat tagihan otomatis",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleManualGenerate = async () => {
    if (!manualForm.resident_id)
      return toast.error("Pilih penghuni terlebih dahulu");
    setIsSubmitting(true);
    try {
      const response = await api.post("/bills/manual", {
        resident_id: Number(manualForm.resident_id),
        duration: Number(manualForm.duration),
      });
      if (response.data.success) {
        toast.success(
          response.data.message || "Tagihan manual berhasil dibuat",
        );
        setIsManualGenerateDialogOpen(false);
        setManualForm({ resident_id: "", duration: "1" });
        fetchBills();
      }
    } catch (error: any) {
      toast.error(
        error.response?.data?.message || "Gagal membuat tagihan manual",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDeleteBill = async () => {
    if (!selectedBillForDelete) return;
    setIsDeleting(true);
    try {
      const response = await api.delete(`/bills/${selectedBillForDelete}`);
      if (response.data.success) {
        toast.success(response.data.message || "Tagihan berhasil dihapus");
        setSelectedBillForDelete(null);
        fetchBills();
      }
    } catch (error: any) {
      toast.error(error.response?.data?.message || "Gagal menghapus tagihan");
    } finally {
      setIsDeleting(false);
    }
  };

  // ========== SINGLE PAYMENT ==========
  const openSinglePayment = (bill: Bill) => {
    setSelectedSingleBill(bill);
    setSinglePaymentAmount(String(bill.amount_due - bill.total_paid));
    setIsSinglePaymentOpen(true);
  };

  const handleSinglePaymentSubmit = async () => {
    if (!selectedSingleBill) return;
    const amount = Number(singlePaymentAmount);
    if (amount <= 0) return toast.error("Nominal tidak valid");

    setIsSubmitting(true);
    try {
      const payload = {
        resident_id: selectedSingleBill.resident_id,
        payment_date: new Date().toISOString().split("T")[0],
        details: [
          {
            bill_id: selectedSingleBill.bill_id,
            amount: amount,
          },
        ],
      };

      const response = await api.post("/payments", payload);
      if (response.data.success) {
        toast.success("Pembayaran berhasil diproses");
        setIsSinglePaymentOpen(false);
        fetchBills();
        fetchPayments();
      }
    } catch (error: any) {
      toast.error(
        error.response?.data?.message || "Terjadi kesalahan saat membayar",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  // ========== MULTI PAYMENT ==========
  useEffect(() => {
    if (!multiForm.resident_id) {
      setResidentBills([]);
      setSelectedMultiBills([]);
      return;
    }
    const fetchResidentBills = async () => {
      setIsLoadingResidentBills(true);
      try {
        const response = await api.get<APIResponse<Bill[]>>(
          `/bills/resident/${multiForm.resident_id}?active_only=true`,
        );
        if (response.data.success) {
          setResidentBills(response.data.data);
          setSelectedMultiBills([]);
        }
      } catch (error) {
        toast.error("Gagal mengambil tagihan warga");
      } finally {
        setIsLoadingResidentBills(false);
      }
    };
    fetchResidentBills();
  }, [multiForm.resident_id]);

  const toggleMultiBill = (bill_id: number) => {
    setSelectedMultiBills((prev) =>
      prev.includes(bill_id)
        ? prev.filter((id) => id !== bill_id)
        : [...prev, bill_id],
    );
  };

  const totalToPay = residentBills
    .filter((b) => selectedMultiBills.includes(b.bill_id))
    .reduce((sum, b) => sum + (b.amount_due - b.total_paid), 0);

  const inputAmount = Number(multiForm.total_amount) || 0;
  const isMultiPaymentDisabled =
    isSubmitting ||
    selectedMultiBills.length === 0 ||
    inputAmount <= 0 ||
    totalToPay > inputAmount;
  const isWarningMulti = totalToPay > inputAmount && inputAmount > 0;

  const handleMultiPaymentSubmit = async () => {
    if (selectedMultiBills.length === 0 || inputAmount <= 0) return;
    setIsSubmitting(true);

    try {
      const payload = {
        resident_id: Number(multiForm.resident_id),
        payment_date: new Date().toISOString().split("T")[0],
        details: selectedMultiBills.map((billId) => {
          const b = residentBills.find((x) => x.bill_id === billId);
          return {
            bill_id: billId,
            amount: b ? b.amount_due - b.total_paid : 0,
          };
        }),
      };

      const response = await api.post("/payments", payload);
      if (response.data.success) {
        toast.success("Pembayaran berhasil dicatat");
        setIsMultiPaymentOpen(false);
        setMultiForm({ resident_id: "", total_amount: "" });
        fetchBills();
        fetchPayments();
      }
    } catch (error: any) {
      toast.error(error.response?.data?.message || "Gagal mencatat pembayaran");
    } finally {
      setIsSubmitting(false);
    }
  };

  // Helper ui icons
  const statusIcon = (status: string) => {
    switch (status) {
      case "paid":
        return <CheckCircle2 className="h-4 w-4 text-emerald-500" />;
      case "partial":
        return <Clock className="h-4 w-4 text-amber-500" />;
      default:
        return <XCircle className="h-4 w-4 text-red-500" />;
    }
  };

  const statusBadge = (status: string) => {
    const styles: Record<string, string> = {
      paid: "bg-emerald-50 text-emerald-700 hover:bg-emerald-50",
      partial: "bg-amber-50 text-amber-700 hover:bg-amber-50",
      unpaid: "bg-red-50 text-red-700 hover:bg-red-50",
    };
    const labels: Record<string, string> = {
      paid: "Lunas",
      partial: "Sebagian",
      unpaid: "Belum Bayar",
    };
    const s = status as keyof typeof labels;
    return (
      <Badge
        variant="secondary"
        className={`rounded-lg text-[10px] uppercase font-bold tracking-tight px-2 py-0.5 ${styles[s]}`}
      >
        {labels[s] || status}
      </Badge>
    );
  };

  return (
    <div className="space-y-6">
      <Tabs defaultValue="tagihan" className="space-y-6">
        <TabsList className="bg-[#DBE2EF]/40 rounded-xl p-1">
          <TabsTrigger
            value="tagihan"
            className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm px-6"
          >
            Tagihan
          </TabsTrigger>
          <TabsTrigger
            value="pembayaran"
            className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm px-6"
          >
            Pembayaran
          </TabsTrigger>
        </TabsList>

        {/* ========== TAB: TAGIHAN ========== */}
        <TabsContent value="tagihan" className="space-y-4">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 w-full sm:w-auto">
              <div className="relative w-full sm:w-72">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Cari warga atau rumah..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-9 rounded-xl border-[#DBE2EF] focus-visible:ring-[#3F72AF]/30"
                />
              </div>
            </div>

            <div className="flex gap-2 w-full sm:w-auto">
              <Button
                variant="outline"
                onClick={() => setIsManualGenerateDialogOpen(true)}
                className="rounded-xl border-[#DBE2EF]"
              >
                <FilePlus className="h-4 w-4 mr-2" />
                Tambah Tagihan Baru
              </Button>
              <Button
                onClick={() => setIsAutoGenerateDialogOpen(true)}
                className="bg-[#3F72AF] hover:bg-[#3F72AF]/90 text-white rounded-xl shadow-sm"
              >
                <CalendarDays className="h-4 w-4 mr-2" />
                Buat Tagihan Otomatis
              </Button>
            </div>
          </div>

          <Card className="border-0 shadow-sm rounded-2xl bg-white">
            <CardHeader className="pb-3 text-base font-semibold text-[#112D4E]">
              Daftar Tagihan ({filteredBills.length})
            </CardHeader>
            <CardContent>
              {isLoadingBills ? (
                <div className="flex flex-col items-center justify-center py-20 text-[#3F72AF]">
                  <Loader2 className="h-8 w-8 animate-spin" />
                </div>
              ) : filteredBills.length === 0 ? (
                <div className="py-16 text-center text-muted-foreground">
                  Tidak ada tagihan yang ditemukan.
                </div>
              ) : (
                <div className="rounded-xl overflow-hidden border border-[#DBE2EF]/60">
                  <Table>
                    <TableHeader className="bg-[#F9F7F7]">
                      <TableRow>
                        <TableHead>Warga</TableHead>
                        <TableHead>Rumah</TableHead>
                        <TableHead>Periode</TableHead>
                        <TableHead>Jenis</TableHead>
                        <TableHead className="text-right">Jumlah</TableHead>
                        <TableHead className="text-right">
                          Sisa / Status
                        </TableHead>
                        <TableHead className="text-right">Aksi</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredBills.map((bill) => (
                        <TableRow key={bill.bill_id}>
                          <TableCell className="font-medium text-[#112D4E]">
                            {bill.resident_name}
                          </TableCell>
                          <TableCell className="text-muted-foreground">
                            {bill.house_number}
                          </TableCell>
                          <TableCell>{bill.period}</TableCell>
                          <TableCell>
                            <Badge variant="outline">{bill.payment_type}</Badge>
                          </TableCell>
                          <TableCell className="text-right">
                            {formatRupiah(bill.amount_due)}
                          </TableCell>
                          <TableCell className="text-right">
                            <div className="text-sm font-semibold">
                              {formatRupiah(
                                bill.amount_due - bill.total_paid > 0
                                  ? bill.amount_due - bill.total_paid
                                  : 0,
                              )}
                            </div>
                            <div className="flex items-center justify-end gap-1 mt-1">
                              {statusIcon(bill.status)}{" "}
                              {statusBadge(bill.status)}
                            </div>
                          </TableCell>
                          <TableCell className="text-right">
                            <div className="flex justify-end gap-2">
                              {bill.status !== "paid" && (
                                <Button
                                  size="sm"
                                  onClick={() => openSinglePayment(bill)}
                                  className="h-8 rounded-lg bg-emerald-50 text-emerald-600 hover:bg-emerald-100 border-0"
                                >
                                  <Wallet className="h-3 w-3 mr-1.5" />
                                  Bayar
                                </Button>
                              )}
                              {bill.status !== "paid" &&
                                bill.status !== "partial" && (
                                  <Button
                                    size="sm"
                                    variant="ghost"
                                    onClick={() =>
                                      setSelectedBillForDelete(bill.bill_id)
                                    }
                                    className="h-8 w-8 p-0 rounded-lg text-red-500 hover:bg-red-50 hover:text-red-600"
                                  >
                                    <Trash2 className="h-4 w-4" />
                                  </Button>
                                )}
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ========== TAB: PEMBAYARAN ========== */}
        <TabsContent value="pembayaran" className="space-y-4">
          <div className="flex justify-end mb-4">
            <Button
              onClick={() => setIsMultiPaymentOpen(true)}
              className="bg-[#3F72AF] hover:bg-[#3F72AF]/90 text-white rounded-xl shadow-sm"
            >
              <HandCoins className="h-4 w-4 mr-2" />
              Tambah Pembayaran
            </Button>
          </div>

          <Card className="border-0 shadow-sm rounded-2xl bg-white">
            <CardHeader className="pb-3 text-base font-semibold text-[#112D4E]">
              Data Pembayaran Selesai ({payments.length})
            </CardHeader>
            <CardContent>
              {isLoadingPayments ? (
                <div className="flex flex-col items-center justify-center py-20 text-[#3F72AF]">
                  <Loader2 className="h-8 w-8 animate-spin" />
                </div>
              ) : payments.length === 0 ? (
                <div className="py-16 text-center text-muted-foreground">
                  Belum ada riwayat pembayaran yang tercatat.
                </div>
              ) : (
                <div className="space-y-2">
                  {payments.map((payment) => (
                    <div
                      key={payment.id}
                      className="rounded-xl border border-[#DBE2EF]/60 overflow-hidden"
                    >
                      <button
                        className="w-full flex items-center justify-between p-4 hover:bg-[#F9F7F7] transition-colors text-left"
                        onClick={() =>
                          setExpandedPayment(
                            expandedPayment === payment.id ? null : payment.id,
                          )
                        }
                      >
                        <div className="flex items-center gap-3">
                          <div className="h-9 w-9 rounded-lg bg-emerald-50 flex items-center justify-center shrink-0">
                            <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                          </div>
                          <div>
                            <p className="text-sm font-medium text-[#112D4E]">
                              {payment.resident?.full_name || "Tidak Diketahui"}
                            </p>
                            <p className="text-xs text-muted-foreground">
                              {formatDateShort(payment.payment_date)}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-3 shrink-0 ml-4">
                          <span className="text-sm font-semibold text-emerald-600">
                            {formatRupiah(payment.total_amount)}
                          </span>
                          {expandedPayment === payment.id ? (
                            <ChevronDown className="h-4 w-4 text-muted-foreground" />
                          ) : (
                            <ChevronRight className="h-4 w-4 text-muted-foreground" />
                          )}
                        </div>
                      </button>
                      {expandedPayment === payment.id && (
                        <div className="px-4 pb-4 pt-0">
                          <div className="rounded-lg bg-[#F9F7F7] p-3 space-y-2 text-sm">
                            <p className="text-xs font-semibold text-[#112D4E]/70 uppercase tracking-wider mb-2">
                              Rincian Tagihan yang Dibayar
                            </p>
                            {payment.details?.map((alloc) => (
                              <div
                                key={alloc.id}
                                className="flex justify-between items-center text-muted-foreground"
                              >
                                <div>
                                  <span className="h-1.5 w-1.5 rounded-full inline-block bg-[#3F72AF] mr-2"></span>
                                  {alloc.bill?.payment_type?.name}
                                </div>
                                <span className="text-[#112D4E] font-medium">
                                  {formatRupiah(alloc.amount)}
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* ========== MODALS ========== */}

      {/* 1. Modals Bill Generation */}
      <Dialog
        open={isAutoGenerateDialogOpen}
        onOpenChange={(open) => {
          if (!isSubmitting) setIsAutoGenerateDialogOpen(open);
        }}
      >
        <DialogContent
          className="sm:max-w-md rounded-2xl border-[#DBE2EF] shadow-lg"
          onPointerDownOutside={(e) => {
            if (isSubmitting) e.preventDefault();
          }}
        >
          <DialogHeader>
            <DialogTitle className="text-[#112D4E] flex items-center gap-2">
              <CalendarDays className="h-5 w-5 text-[#3F72AF]" />
              Buat Tagihan Otomatis
            </DialogTitle>
            <DialogDescription>
              Apakah Anda yakin ingin membuat tagihan untuk semua warga secara
              otomatis untuk periode bulan ini?
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 sm:gap-0 mt-4 space-x-2">
            <Button
              variant="outline"
              onClick={() => setIsAutoGenerateDialogOpen(false)}
              disabled={isSubmitting}
              className="rounded-xl border-[#DBE2EF]"
            >
              Batal
            </Button>
            <Button
              onClick={handleAutoGenerate}
              disabled={isSubmitting}
              className="bg-[#3F72AF] hover:bg-[#3F72AF]/90 text-white rounded-xl shadow-md min-w-[120px]"
            >
              {isSubmitting ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                "Buat Tagihan"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog
        open={isManualGenerateDialogOpen}
        onOpenChange={(open) => {
          if (!isSubmitting) setIsManualGenerateDialogOpen(open);
        }}
      >
        <DialogContent
          className="sm:max-w-md rounded-2xl border-[#DBE2EF] shadow-lg"
          onPointerDownOutside={(e) => {
            if (isSubmitting) e.preventDefault();
          }}
        >
          <DialogHeader>
            <DialogTitle className="text-[#112D4E] flex items-center gap-2">
              <FilePlus className="h-5 w-5 text-[#3F72AF]" />
              Tambah Tagihan Manual
            </DialogTitle>
            <DialogDescription>
              Pilih warga dan durasi bulan untuk membuat tagihan baru secara
              manual.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label className="text-[#112D4E] font-medium">Penghuni</Label>
              <Select
                onValueChange={(v) =>
                  setManualForm({ ...manualForm, resident_id: v })
                }
              >
                <SelectTrigger className="rounded-xl border-[#DBE2EF]">
                  <SelectValue placeholder="Pilih..." />
                </SelectTrigger>
                <SelectContent>
                  {residents.map((r) => (
                    <SelectItem key={r.id} value={r.id.toString()}>
                      {r.full_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-[#112D4E] font-medium">Durasi</Label>
              <Select
                onValueChange={(v) =>
                  setManualForm({ ...manualForm, duration: v })
                }
              >
                <SelectTrigger className="rounded-xl border-[#DBE2EF]">
                  <SelectValue placeholder="Bulan" />
                </SelectTrigger>
                <SelectContent>
                  {[...Array(12)].map((_, i) => (
                    <SelectItem key={i + 1} value={`${i + 1}`}>
                      {i + 1} Bulan
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter className="gap-2 space-x-2 sm:gap-0">
            <Button
              variant="outline"
              onClick={() => setIsManualGenerateDialogOpen(false)}
              disabled={isSubmitting}
              className="rounded-xl border-[#DBE2EF]"
            >
              Batal
            </Button>
            <Button
              onClick={handleManualGenerate}
              disabled={isSubmitting}
              className="bg-[#3F72AF] hover:bg-[#3F72AF]/90 text-white rounded-xl shadow-md min-w-[100px]"
            >
              {isSubmitting ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                "Simpan"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 2. Modal Single Payment */}
      <Dialog open={isSinglePaymentOpen} onOpenChange={setIsSinglePaymentOpen}>
        <DialogContent className="sm:max-w-md rounded-2xl border-[#DBE2EF]">
          <DialogHeader>
            <DialogTitle>Bayar Tagihan</DialogTitle>
            <DialogDescription>
              Rincian tagihan warga terpilih
            </DialogDescription>
          </DialogHeader>
          {selectedSingleBill && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm bg-slate-50 p-4 rounded-xl border border-slate-100">
                <div>
                  <span className="text-muted-foreground block text-xs">
                    Penghuni
                  </span>
                  <span className="font-semibold text-slate-800">
                    {selectedSingleBill.resident_name}
                  </span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-xs">
                    Periode
                  </span>
                  <span className="font-semibold text-slate-800">
                    {selectedSingleBill.period}
                  </span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-xs">
                    Jenis
                  </span>
                  <span className="font-semibold text-slate-800">
                    {selectedSingleBill.payment_type}
                  </span>
                </div>
                <div>
                  <span className="text-muted-foreground block text-xs">
                    Sisa Tunggakan
                  </span>
                  <span className="font-semibold text-red-600">
                    {formatRupiah(
                      selectedSingleBill.amount_due -
                        selectedSingleBill.total_paid,
                    )}
                  </span>
                </div>
              </div>
              <div className="space-y-2">
                <Label>
                  Nominal Dibayar (Rp) <span className="text-red-500">*</span>
                </Label>
                <Input
                  type="number"
                  value={singlePaymentAmount}
                  onChange={(e) => setSinglePaymentAmount(e.target.value)}
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsSinglePaymentOpen(false)}
            >
              Batal
            </Button>
            <Button
              onClick={handleSinglePaymentSubmit}
              disabled={isSubmitting}
              className="bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm"
            >
              {isSubmitting ? (
                <Loader2 className="animate-spin" />
              ) : (
                "Konfirmasi Pembayaran"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 3. Modal Multi Payment */}
      <Dialog
        open={isMultiPaymentOpen}
        onOpenChange={(open) => {
          setIsMultiPaymentOpen(open);
          if (!open) {
            setMultiForm({ resident_id: "", total_amount: "" });
            setResidentBills([]);
            setSelectedMultiBills([]);
          }
        }}
      >
        <DialogContent className="sm:max-w-2xl rounded-2xl border-[#DBE2EF]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <HandCoins className="h-5 w-5 text-[#3F72AF]" />
              Tambah Pembayaran
            </DialogTitle>
          </DialogHeader>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 py-2">
            <div className="space-y-2">
              <Label>Pilih Penghuni</Label>
              <Select
                value={multiForm.resident_id}
                onValueChange={(v) =>
                  setMultiForm({ ...multiForm, resident_id: v })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Pilih..." />
                </SelectTrigger>
                <SelectContent>
                  {residents.map((r) => (
                    <SelectItem key={r.id} value={r.id.toString()}>
                      {r.full_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Total Saldo/Uang (Rp)</Label>
              <Input
                type="number"
                value={multiForm.total_amount}
                onChange={(e) =>
                  setMultiForm({ ...multiForm, total_amount: e.target.value })
                }
                placeholder="Contoh: 200000"
              />
            </div>
          </div>

          {multiForm.resident_id && (
            <div className="mt-2 space-y-4">
              <Label>Pilih Tagihan yang Dibayar</Label>
              <div className="border border-[#DBE2EF] rounded-xl overflow-y-auto max-h-56">
                <Table>
                  <TableHeader className="bg-[#F9F7F7]">
                    <TableRow>
                      <TableHead className="w-[50px] text-center"></TableHead>
                      <TableHead>Periode</TableHead>
                      <TableHead>Jenis</TableHead>
                      <TableHead className="text-right">Tunggakan</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {isLoadingResidentBills ? (
                      <TableRow>
                        <TableCell colSpan={4} className="text-center py-8">
                          <Loader2 className="h-6 w-6 animate-spin mx-auto text-[#3F72AF]/50" />
                        </TableCell>
                      </TableRow>
                    ) : residentBills.length === 0 ? (
                      <TableRow>
                        <TableCell
                          colSpan={4}
                          className="text-center text-muted-foreground py-8"
                        >
                          Tidak ada tagihan tertunda
                        </TableCell>
                      </TableRow>
                    ) : (
                      residentBills.map((bill) => (
                        <TableRow
                          key={bill.bill_id}
                          className={
                            selectedMultiBills.includes(bill.bill_id)
                              ? "bg-emerald-50/40"
                              : ""
                          }
                        >
                          <TableCell className="text-center">
                            <Checkbox
                              checked={selectedMultiBills.includes(
                                bill.bill_id,
                              )}
                              onCheckedChange={() =>
                                toggleMultiBill(bill.bill_id)
                              }
                            />
                          </TableCell>
                          <TableCell>{bill.period}</TableCell>
                          <TableCell>
                            <Badge variant="outline" className="text-[10px]">
                              {bill.payment_type}
                            </Badge>
                          </TableCell>
                          <TableCell className="text-right font-medium">
                            {formatRupiah(bill.amount_due - bill.total_paid)}
                          </TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </div>

              <div className="bg-slate-50 border border-slate-100 rounded-xl p-4 flex items-center justify-between">
                <div>
                  <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">
                    Total Tagihan (Dipilih)
                  </p>
                  <p className="text-lg font-bold text-[#112D4E]">
                    {formatRupiah(totalToPay)}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold">
                    Kembalian (Change)
                  </p>
                  <p
                    className={`text-lg font-bold ${isWarningMulti ? "text-red-500" : "text-emerald-600"}`}
                  >
                    {inputAmount >= totalToPay
                      ? formatRupiah(inputAmount - totalToPay)
                      : "-"}
                  </p>
                </div>
              </div>

              {isWarningMulti && (
                <div className="flex bg-red-50 text-red-600 p-3 rounded-xl border border-red-100 text-sm items-start gap-2">
                  <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
                  <p>
                    Total uang yang diberikan tidak cukup untuk membayar tagihan
                    yang dipilih.
                  </p>
                </div>
              )}
            </div>
          )}

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsMultiPaymentOpen(false)}
            >
              Batal
            </Button>
            <Button
              onClick={handleMultiPaymentSubmit}
              disabled={isMultiPaymentDisabled}
              className="bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm min-w-[120px]"
            >
              {isSubmitting ? (
                <Loader2 className="animate-spin" />
              ) : (
                "Bayar Sekarang"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmModal
        isOpen={selectedBillForDelete !== null}
        onClose={() => !isDeleting && setSelectedBillForDelete(null)}
        onConfirm={handleDeleteBill}
        header={
          <div className="flex items-center gap-2">
            <Trash2 className="h-5 w-5 text-red-500" />
            Hapus Tagihan
          </div>
        }
        body="Apakah Anda yakin ingin menghapus tagihan ini? Tindakan ini tidak dapat dibatalkan."
        footer={
          <DialogFooter className="gap-2 sm:gap-0 mt-4 space-x-2">
            <Button
              variant="outline"
              onClick={() => setSelectedBillForDelete(null)}
              disabled={isDeleting}
              className="rounded-xl border-[#DBE2EF] flex-1 sm:flex-none"
            >
              Batal
            </Button>
            <Button
              onClick={handleDeleteBill}
              disabled={isDeleting}
              className="bg-red-600 hover:bg-red-700 text-white rounded-xl shadow-md min-w-[120px] flex-1 sm:flex-none"
            >
              {isDeleting ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                  Menghapus...
                </>
              ) : (
                "Ya, Hapus"
              )}
            </Button>
          </DialogFooter>
        }
      />
    </div>
  );
}
